name: Issue/Bug Report
description: Create an issue or bug report
title: "Title"
labels: ["bug", "investigating"]
assignees:
  - "ProbablyRaging"
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: A clear and concise description of your issue or bug
      placeholder: Include any steps that might help reproduced the issue, screenshots of the issue, a dev tools log (f12)
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version of HYS are you using?
      options:
        - Latest version
        - Older version
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Vivaldi
        - Microsoft Edge
        - Other
    validations:
      required: true
  - type: dropdown
    id: browser-version
    attributes:
      label: Latest browser version?
      options: 
        - 'Yes'
        - 'No'
    validations:
      required: true
